-- 1. Drop the "Leaf" tables (Children)
DROP TABLE IF EXISTS USAGE_LOGS CASCADE;
DROP TABLE IF EXISTS SYSTEM_EVENTS CASCADE;
DROP TABLE IF EXISTS NETWORK_SESSIONS CASCADE;
DROP TABLE IF EXISTS ALLOCATIONS CASCADE;
DROP TABLE IF EXISTS MAINTENANCE_LOG CASCADE;

-- 2. Drop the "Branch" tables (Intermediate)
DROP TABLE IF EXISTS PROCESSES CASCADE;
DROP TABLE IF EXISTS RESOURCES CASCADE;

-- 3. Drop the "Root" tables (Parents)
DROP TABLE IF EXISTS USERS CASCADE;
DROP TABLE IF EXISTS EXECUTABLES CASCADE;
DROP TABLE IF EXISTS RESOURCE_TYPES CASCADE;