-- 1. Parent Tables
SELECT * FROM USERS;
SELECT * FROM EXECUTABLES;
SELECT * FROM RESOURCE_TYPES;

-- 2. Core Tables
SELECT * FROM PROCESSES;
SELECT * FROM RESOURCES;

-- 3. Child/Log Tables
SELECT * FROM USAGE_LOGS;
SELECT * FROM SYSTEM_EVENTS;
SELECT * FROM MAINTENANCE_LOG;
SELECT * FROM ALLOCATIONS;
SELECT * FROM NETWORK_SESSIONS;